<template>
  <div>
    <SunlightTable
      :data="tableData"
      :columns="columns"
      :toolbar-config="toolbarConfig"
      :show-pagination="true"
      v-model:current-page="currentPage"
      v-model:page-size="pageSize"
      :total="total"
      @refresh="handleRefresh"
    />
  </div>
</template>

<script setup>
import { ref, reactive, watch } from "vue";
import { SunlightTable } from "sunlight-ui";

const toolbarConfig = reactive({
  showDensity: true,
  showColumnConfig: true,
  showRefresh: true,
  customButtons: [
    {
      key: "add",
      label: "新增",
      icon: "Plus",
      type: "primary",
      position: "left",
    },
    {
      key: "batch-delete",
      label: "批量删除",
      icon: "Delete",
      type: "danger",
      position: "left",
    },
  ],
});

const tableData = ref([]);
const currentPage = ref(1);
const pageSize = ref(10);
const total = ref(30);

const columns = [
  {
    label: "基本信息",
    children: [
      { prop: "id", label: "ID", width: 70 },
      { prop: "name", label: "姓名", width: 90 },
      { prop: "gender", label: "性别", width: 70 },
      { prop: "age", label: "年龄", width: 70 },
      { prop: "phone", label: "手机号", width: 140 },
    ],
  },
  {
    label: "联系信息",
    children: [
      { prop: "email", label: "邮箱", width: 200 },
      { prop: "city", label: "城市", width: 100 },
      { prop: "address", label: "详细地址", width: 250 },
    ],
  },
  {
    label: "工作信息",
    children: [
      { prop: "department", label: "部门", width: 100 },
      { prop: "position", label: "职位", width: 100 },
      { prop: "level", label: "职级", width: 100 },
      { prop: "team", label: "团队", width: 100 },
    ],
  },
  {
    label: "薪资信息",
    children: [
      { prop: "salary", label: "基本薪资", width: 120 },
      { prop: "bonus", label: "绩效奖金", width: 120 },
      { prop: "totalSalary", label: "总薪资", width: 120 },
    ],
  },
  {
    label: "入职信息",
    children: [
      { prop: "entryType", label: "入职类型", width: 100 },
      { prop: "probation", label: "试用期", width: 100 },
      { prop: "joinDate", label: "入职日期", width: 120 },
    ],
  },
  {
    label: "状态信息",
    children: [
      { prop: "status", label: "在职状态", width: 100 },
      { prop: "manager", label: "直属上级", width: 100 },
    ],
  },
];

const allData = [
  {
    id: 1,
    name: "张伟",
    gender: "男",
    age: 25,
    phone: "13800138001",
    email: "user1@example.com",
    city: "北京",
    address: "北京市朝阳区某街道某号",
    department: "技术部",
    position: "员工",
    level: "P2",
    team: "前端组",
    salary: 15000,
    bonus: 3000,
    totalSalary: 18000,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "张经理",
    joinDate: "2022-01-01",
  },
  {
    id: 2,
    name: "李芳",
    gender: "女",
    age: 28,
    phone: "13800138002",
    email: "user2@example.com",
    city: "上海",
    address: "上海市浦东新区某街道某号",
    department: "市场部",
    position: "主管",
    level: "P3",
    team: "市场组",
    salary: 20000,
    bonus: 4000,
    totalSalary: 24000,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "李经理",
    joinDate: "2021-06-15",
  },
  {
    id: 3,
    name: "王娜",
    gender: "女",
    age: 30,
    phone: "13800138003",
    email: "user3@example.com",
    city: "广州",
    address: "广州市天河区某街道某号",
    department: "销售部",
    position: "经理",
    level: "P4",
    team: "销售组",
    salary: 25000,
    bonus: 5000,
    totalSalary: 30000,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "王经理",
    joinDate: "2020-11-01",
  },
  {
    id: 4,
    name: "赵敏",
    gender: "女",
    age: 26,
    phone: "13800138004",
    email: "user4@example.com",
    city: "深圳",
    address: "深圳市南山区某街道某号",
    department: "人事部",
    position: "员工",
    level: "P2",
    team: "人事组",
    salary: 12000,
    bonus: 2400,
    totalSalary: 14400,
    status: "在职",
    entryType: "校招",
    probation: "6个月",
    manager: "赵经理",
    joinDate: "2022-07-01",
  },
  {
    id: 5,
    name: "刘伟",
    gender: "男",
    age: 32,
    phone: "13800138005",
    email: "user5@example.com",
    city: "杭州",
    address: "杭州市西湖区某街道某号",
    department: "财务部",
    position: "主管",
    level: "P3",
    team: "财务组",
    salary: 18000,
    bonus: 3600,
    totalSalary: 21600,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "刘经理",
    joinDate: "2021-03-15",
  },
  {
    id: 6,
    name: "陈静",
    gender: "女",
    age: 27,
    phone: "13800138006",
    email: "user6@example.com",
    city: "南京",
    address: "南京市玄武区某街道某号",
    department: "运营部",
    position: "员工",
    level: "P2",
    team: "运营组",
    salary: 13000,
    bonus: 2600,
    totalSalary: 15600,
    status: "在职",
    entryType: "内推",
    probation: "3个月",
    manager: "张经理",
    joinDate: "2022-04-01",
  },
  {
    id: 7,
    name: "杨强",
    gender: "男",
    age: 29,
    phone: "13800138007",
    email: "user7@example.com",
    city: "武汉",
    address: "武汉市武昌区某街道某号",
    department: "产品部",
    position: "经理",
    level: "P4",
    team: "产品组",
    salary: 22000,
    bonus: 4400,
    totalSalary: 26400,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "李经理",
    joinDate: "2020-09-15",
  },
  {
    id: 8,
    name: "黄磊",
    gender: "男",
    age: 24,
    phone: "13800138008",
    email: "user8@example.com",
    city: "成都",
    address: "成都市锦江区某街道某号",
    department: "客服部",
    position: "员工",
    level: "P1",
    team: "客服组",
    salary: 10000,
    bonus: 2000,
    totalSalary: 12000,
    status: "试用期",
    entryType: "校招",
    probation: "6个月",
    manager: "王经理",
    joinDate: "2023-01-01",
  },
  {
    id: 9,
    name: "周军",
    gender: "男",
    age: 31,
    phone: "13800138009",
    email: "user9@example.com",
    city: "西安",
    address: "西安市雁塔区某街道某号",
    department: "技术部",
    position: "主管",
    level: "P3",
    team: "后端组",
    salary: 19000,
    bonus: 3800,
    totalSalary: 22800,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "赵经理",
    joinDate: "2021-02-15",
  },
  {
    id: 10,
    name: "吴洋",
    gender: "男",
    age: 26,
    phone: "13800138010",
    email: "user10@example.com",
    city: "重庆",
    address: "重庆市渝中区某街道某号",
    department: "市场部",
    position: "员工",
    level: "P2",
    team: "市场组",
    salary: 14000,
    bonus: 2800,
    totalSalary: 16800,
    status: "在职",
    entryType: "内推",
    probation: "3个月",
    manager: "刘经理",
    joinDate: "2022-05-15",
  },
  {
    id: 11,
    name: "徐勇",
    gender: "男",
    age: 33,
    phone: "13800138011",
    email: "user11@example.com",
    city: "苏州",
    address: "苏州市姑苏区某街道某号",
    department: "销售部",
    position: "总监",
    level: "P5",
    team: "销售组",
    salary: 30000,
    bonus: 6000,
    totalSalary: 36000,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "张经理",
    joinDate: "2020-05-01",
  },
  {
    id: 12,
    name: "孙艳",
    gender: "女",
    age: 28,
    phone: "13800138012",
    email: "user12@example.com",
    city: "天津",
    address: "天津市和平区某街道某号",
    department: "人事部",
    position: "主管",
    level: "P3",
    team: "人事组",
    salary: 16000,
    bonus: 3200,
    totalSalary: 19200,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "李经理",
    joinDate: "2021-08-15",
  },
  {
    id: 13,
    name: "马杰",
    gender: "男",
    age: 29,
    phone: "13800138013",
    email: "user13@example.com",
    city: "长沙",
    address: "长沙市芙蓉区某街道某号",
    department: "财务部",
    position: "经理",
    level: "P4",
    team: "财务组",
    salary: 23000,
    bonus: 4600,
    totalSalary: 27600,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "王经理",
    joinDate: "2020-12-01",
  },
  {
    id: 14,
    name: "朱娟",
    gender: "女",
    age: 27,
    phone: "13800138014",
    email: "user14@example.com",
    city: "郑州",
    address: "郑州市金水区某街道某号",
    department: "运营部",
    position: "主管",
    level: "P3",
    team: "运营组",
    salary: 17000,
    bonus: 3400,
    totalSalary: 20400,
    status: "在职",
    entryType: "内推",
    probation: "3个月",
    manager: "赵经理",
    joinDate: "2021-11-15",
  },
  {
    id: 15,
    name: "胡涛",
    gender: "男",
    age: 30,
    phone: "13800138015",
    email: "user15@example.com",
    city: "青岛",
    address: "青岛市市南区某街道某号",
    department: "产品部",
    position: "总监",
    level: "P5",
    team: "产品组",
    salary: 28000,
    bonus: 5600,
    totalSalary: 33600,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "刘经理",
    joinDate: "2020-08-01",
  },
  {
    id: 16,
    name: "郭霞",
    gender: "女",
    age: 25,
    phone: "13800138016",
    email: "user16@example.com",
    city: "北京",
    address: "北京市海淀区某街道某号",
    department: "客服部",
    position: "员工",
    level: "P1",
    team: "客服组",
    salary: 11000,
    bonus: 2200,
    totalSalary: 13200,
    status: "在职",
    entryType: "校招",
    probation: "6个月",
    manager: "张经理",
    joinDate: "2022-09-15",
  },
  {
    id: 17,
    name: "林明",
    gender: "男",
    age: 31,
    phone: "13800138017",
    email: "user17@example.com",
    city: "上海",
    address: "上海市静安区某街道某号",
    department: "技术部",
    position: "经理",
    level: "P4",
    team: "移动端组",
    salary: 24000,
    bonus: 4800,
    totalSalary: 28800,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "李经理",
    joinDate: "2020-10-01",
  },
  {
    id: 18,
    name: "何秀英",
    gender: "女",
    age: 32,
    phone: "13800138018",
    email: "user18@example.com",
    city: "广州",
    address: "广州市越秀区某街道某号",
    department: "市场部",
    position: "总监",
    level: "P5",
    team: "市场组",
    salary: 29000,
    bonus: 5800,
    totalSalary: 34800,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "王经理",
    joinDate: "2020-07-15",
  },
  {
    id: 19,
    name: "高华",
    gender: "男",
    age: 28,
    phone: "13800138019",
    email: "user19@example.com",
    city: "深圳",
    address: "深圳市福田区某街道某号",
    department: "销售部",
    position: "主管",
    level: "P3",
    team: "销售组",
    salary: 18000,
    bonus: 3600,
    totalSalary: 21600,
    status: "在职",
    entryType: "内推",
    probation: "3个月",
    manager: "赵经理",
    joinDate: "2021-04-15",
  },
  {
    id: 20,
    name: "罗平",
    gender: "男",
    age: 26,
    phone: "13800138020",
    email: "user20@example.com",
    city: "杭州",
    address: "杭州市余杭区某街道某号",
    department: "技术部",
    position: "员工",
    level: "P2",
    team: "测试组",
    salary: 14000,
    bonus: 2800,
    totalSalary: 16800,
    status: "在职",
    entryType: "校招",
    probation: "6个月",
    manager: "刘经理",
    joinDate: "2022-06-01",
  },
  {
    id: 21,
    name: "张志",
    gender: "男",
    age: 29,
    phone: "13800138021",
    email: "user21@example.com",
    city: "南京",
    address: "南京市建邺区某街道某号",
    department: "财务部",
    position: "员工",
    level: "P2",
    team: "财务组",
    salary: 13000,
    bonus: 2600,
    totalSalary: 15600,
    status: "在职",
    entryType: "内推",
    probation: "3个月",
    manager: "张经理",
    joinDate: "2022-03-15",
  },
  {
    id: 22,
    name: "王丽",
    gender: "女",
    age: 27,
    phone: "13800138022",
    email: "user22@example.com",
    city: "武汉",
    address: "武汉市洪山区某街道某号",
    department: "运营部",
    position: "员工",
    level: "P2",
    team: "运营组",
    salary: 12000,
    bonus: 2400,
    totalSalary: 14400,
    status: "在职",
    entryType: "校招",
    probation: "6个月",
    manager: "李经理",
    joinDate: "2022-10-01",
  },
  {
    id: 23,
    name: "李强",
    gender: "男",
    age: 30,
    phone: "13800138023",
    email: "user23@example.com",
    city: "成都",
    address: "成都市武侯区某街道某号",
    department: "产品部",
    position: "主管",
    level: "P3",
    team: "产品组",
    salary: 19000,
    bonus: 3800,
    totalSalary: 22800,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "王经理",
    joinDate: "2021-07-15",
  },
  {
    id: 24,
    name: "赵静",
    gender: "女",
    age: 26,
    phone: "13800138024",
    email: "user24@example.com",
    city: "西安",
    address: "西安市碑林区某街道某号",
    department: "人事部",
    position: "员工",
    level: "P2",
    team: "人事组",
    salary: 11000,
    bonus: 2200,
    totalSalary: 13200,
    status: "试用期",
    entryType: "校招",
    probation: "6个月",
    manager: "赵经理",
    joinDate: "2023-02-15",
  },
  {
    id: 25,
    name: "刘杰",
    gender: "男",
    age: 31,
    phone: "13800138025",
    email: "user25@example.com",
    city: "重庆",
    address: "重庆市江北区某街道某号",
    department: "技术部",
    position: "经理",
    level: "P4",
    team: "运维组",
    salary: 23000,
    bonus: 4600,
    totalSalary: 27600,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "刘经理",
    joinDate: "2020-12-15",
  },
  {
    id: 26,
    name: "陈丽",
    gender: "女",
    age: 28,
    phone: "13800138026",
    email: "user26@example.com",
    city: "苏州",
    address: "苏州市工业园区某街道某号",
    department: "市场部",
    position: "主管",
    level: "P3",
    team: "市场组",
    salary: 17000,
    bonus: 3400,
    totalSalary: 20400,
    status: "在职",
    entryType: "内推",
    probation: "3个月",
    manager: "张经理",
    joinDate: "2021-05-15",
  },
  {
    id: 27,
    name: "杨磊",
    gender: "男",
    age: 29,
    phone: "13800138027",
    email: "user27@example.com",
    city: "天津",
    address: "天津市滨海新区某街道某号",
    department: "销售部",
    position: "员工",
    level: "P2",
    team: "销售组",
    salary: 14000,
    bonus: 2800,
    totalSalary: 16800,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "李经理",
    joinDate: "2022-01-15",
  },
  {
    id: 28,
    name: "黄军",
    gender: "男",
    age: 32,
    phone: "13800138028",
    email: "user28@example.com",
    city: "长沙",
    address: "长沙市岳麓区某街道某号",
    department: "技术部",
    position: "总监",
    level: "P5",
    team: "AI组",
    salary: 32000,
    bonus: 6400,
    totalSalary: 38400,
    status: "在职",
    entryType: "社招",
    probation: "3个月",
    manager: "王经理",
    joinDate: "2020-06-01",
  },
  {
    id: 29,
    name: "周敏",
    gender: "女",
    age: 26,
    phone: "13800138029",
    email: "user29@example.com",
    city: "郑州",
    address: "郑州市中原区某街道某号",
    department: "客服部",
    position: "员工",
    level: "P1",
    team: "客服组",
    salary: 10000,
    bonus: 2000,
    totalSalary: 12000,
    status: "在职",
    entryType: "校招",
    probation: "6个月",
    manager: "赵经理",
    joinDate: "2022-11-01",
  },
  {
    id: 30,
    name: "吴芳",
    gender: "女",
    age: 27,
    phone: "13800138030",
    email: "user30@example.com",
    city: "青岛",
    address: "青岛市崂山区某街道某号",
    department: "产品部",
    position: "员工",
    level: "P2",
    team: "产品组",
    salary: 13000,
    bonus: 2600,
    totalSalary: 15600,
    status: "在职",
    entryType: "内推",
    probation: "3个月",
    manager: "刘经理",
    joinDate: "2022-08-15",
  },
];

function fetchTableData(page = 1, pageSizeVal = 10) {
  return new Promise(resolve => {
    setTimeout(() => {
      const start = (page - 1) * pageSizeVal;
      const end = start + pageSizeVal;
      resolve({
        data: allData.slice(start, end),
        total: allData.length,
      });
    }, 300);
  });
}

const loadData = async () => {
  const result = await fetchTableData(currentPage.value, pageSize.value);
  tableData.value = result.data;
  total.value = result.total;
};

const handleRefresh = () => {
  loadData();
};

watch([currentPage, pageSize], () => {
  loadData();
});

loadData();
</script>
